### ISSUE TITLE
As an entrepreneur, I want to log out in order to leave the website securely.

### ISSUE THREAD

**Issue by arianafernandes** [pedro-c/UPM-ideask#19]
Acceptance Criteria: 
- [U] In all pages there is a “Logout” button visible.
- [U] In all pages, when I click the button “Logout” a message appears, asking for confirmation  “Do you really want to log out”, together with two buttons saying “yes” and “no”.
- [U] After I have confirmed the logout, a success message appears and the I am lead to the main page with the “Register” button and “Login” button visible.

**Comment by c-pius** [comment]
- [x] In all pages there is a “Logout” button visible.
- [x] In all pages, when I click the button “Logout” a message appears, asking for confirmation  “Do you really want to log out”, together with two buttons saying “yes” and “no”.
- [x] After I have confirmed the logout, a success message appears and the I am lead to the main page with the “Register” button and “Login” button visible.

**Comment by c-pius** [comment]
![image](https://user-images.githubusercontent.com/22994291/48901242-1367ca00-ee55-11e8-89ed-4b1eb29e3250.png)

**Comment by c-pius** [comment]
![image](https://user-images.githubusercontent.com/22994291/48907168-f805ba80-ee66-11e8-8f3f-21ab9a6838ca.png)
