### ISSUE TITLE
As a new user, I want to register for the application in order to access it.

### ISSUE THREAD

**Issue by arianafernandes** [pedro-c/UPM-ideask#2]
Acceptance Criteria: 
- In the main page, when I click the button “Register” then a new page appears (register page) with fields: First Name, last name, email and password. 
- [U] In the register page, when all the fields are completed and I click a button “Save” then a success message appears. Then the main page appears without the “Register” or “Login” buttons visible but with the “Logout” button visible.
- In the register page, when all the fields are not completed and I click a button “Save” then a error message appears (indicating missing field(s)).

**Comment by c-pius** [comment]
**Acceptance Criteria:** 

- [x] - In the main page, when I click the button “Register” then a new page appears (register page) with fields: First Name, last name, email and password. 
- [x] - In the register page, when all the fields are completed and I click a button “Save” then a success message appears. Then the main page appears without the “Register” or “Login” buttons visible but with the “Logout” button visible.
- [x] - In the register page, when all the fields are not completed and I click a button “Save” then a error message appears (indicating missing field(s)).

**Comment by c-pius** [comment]
Tests Before Coding (2 already succeed because invalid input is tested)

![screen shot 2018-11-19 at 21 43 18](https://user-images.githubusercontent.com/22994291/48734759-ae3e8980-ec46-11e8-9cf6-92017f42559e.png)

**Comment by c-pius** [comment]
Tests After Coding

![screen shot 2018-11-19 at 21 58 48](https://user-images.githubusercontent.com/22994291/48734785-c9a99480-ec46-11e8-9fc7-8945c9d9e142.png)
