### ISSUE TITLE
As an entrepreneur, I want to login to the application in order to access my ideas, others ideas and to manage them.

### ISSUE THREAD

**Issue by arianafernandes** [pedro-c/UPM-ideask#20]
Acceptance Criteria: 
- In the main page, when I click the button “Login” then a new page appears (register page) with fields:  email and password. 
- [U] In the login page, when all the fields are not completed then I click a button “Login” and a error message appears (indicating missing field(s)).
- [U] In the login page, when all the fields are completed correctly and then I click a button - “Login” a success message appears. Then the main page appears without the “Register” or “Login” buttons visible but with the “Logout” button visible.
- [U] In the login page, when not all fields are completed an error message appears.
- [U] In the login page, when all the fields are completed but wrong then I click a button “Login” an error message appears.
- [U] In the login page, there is a button saying “register now” that leads me to the register page when clicked.

**Comment by c-pius** [comment]
- [x] In the main page, when I click the button “Login” then a new page appears (register page) with fields:  email and password. 
- [x] In the login page, when all the fields are not completed then I click a button “Login” and a error message appears (indicating missing field(s)).
- [x] In the login page, when all the fields are completed correctly and then I click a button “Login” a success message appears. Then the main page appears without the “Register” or “Login” buttons visible but with the “Logout” button visible.
- [x] In the login page, when not all fields are completed an error message appears.
- [x] In the login page, when all the fields are completed but wrong then I click a button “Login” an error message appears.
- [x] In the login page, there is a button saying “register now” that leads me to the register page when clicked.

**Comment by c-pius** [comment]
![image](https://user-images.githubusercontent.com/22994291/48899519-1ca26800-ee50-11e8-88dc-86b1b77a1528.png)

**Comment by c-pius** [comment]
![image](https://user-images.githubusercontent.com/22994291/48900418-9d626380-ee52-11e8-8f74-f78ad8e129e3.png)
